### ISSUE TITLE
The GET method is not supported for this route. Supported methods: POST.

### ISSUE THREAD

**Issue by Snakzi** [antonioribeiro/google2fa-laravel#116]
I have added Laravel Google2FA with this tutorial: https://www.mynotepaper.com/laravel-two-factor-authentication-with-google-authenticator

However, when it asks me for my OTP and I enter the wrong and after that, I enter the correct password. It redirects me to an error which is "The GET method is not supported for this route. Supported methods: POST."

Eventhough it worked, but it shouldnt post that error.

I think it has something to do with that after I entered a wrong pass, it redirects me to /2fa/2faVerify instead of still being at /dashboard (redirect to my default route in LoginController)

When I enter the correct code at the first try, it does not show me that error and everything is fine.

I tried to rename the route in web.php to any but that doesnt work.

**Comment by geekasso** [comment]
I am having the same issue and you are correct, this is pertaining to

`Route::middleware(['auth', '2fa'])->group(function () {
        Route::post('/2fa', function () {
            return redirect(URL()->previous());
        })->name('2fa');
  });`

The only way I can get it to work is to replace the return redirect() with an explicit redirect route - but this is not ideal since the 2FA can be prompted when it is expired, forcing the user to the dashboard where they have to navigate to the page they were at previously.

`Route::middleware(['auth', '2fa'])->group(function () {
        Route::post('/2fa', function () {
            // return redirect(URL()->previous());
            return redirect()->route('dashboard');
        })->name('2fa');
    });`

How did you eventually get it resolved and are you setting an explicit route?

**Comment by geekasso** [comment]
I am having the same issue and you are correct, this is pertaining to

```
Route::middleware(['auth',` '2fa'])->group(function () {
        Route::post('/2fa', function () {
            return redirect(URL()->previous());
        })->name('2fa');
});
```

The only way I can get it to work is to replace the return redirect() with an explicit redirect route - but this is not ideal since the 2FA can be prompted when it is expired, forcing the user to the dashboard where they have to navigate to the page they were at previously.

```
Route::middleware(['auth', '2fa'])->group(function () {
   Route::post('/2fa', function () {
      // return redirect(URL()->previous());
      return redirect()->route('dashboard');
   })->name('2fa');
});
```

How did you eventually get it resolved and are you setting an explicit route?
