### ISSUE TITLE
How to show text code as well beside the QR code ?

### ISSUE THREAD

**Issue by AghaFarokh** [antonioribeiro/google2fa-laravel#138]
I'm using this on my project and it's working fine but it's only shows the QR code and i don't know how to show the code as text 
guide me
thnks

**Comment by antonioribeiro** [comment]
You should not show the code as text, this is the job of authenticators app, because the code will be used to check if the user has actual access to your application. If you really need it, it's possible because this package extends the Google2FA package, you can use the `getCurrentOtp()` to get it.
