### ISSUE TITLE
Update for Laravel 10

### ISSUE THREAD

**Issue by repat** [antonioribeiro/google2fa-laravel#181]
Hi @antonioribeiro,

could you update the constraint in the `composer.json` to allow for Laravel 10?
Should be easy as 

```json
{
...
"laravel/framework": ">=5.4.36|^8.0|^9.0|^10.0",
...
}
```

Thank you!

**Comment by davidrushton** [comment]
I've created #182 which updates the composer.json, but testing this on my own project I think the current latest release actually works on Laravel 10.x since the the constraint is:

```
"laravel/framework": ">=5.4.36|^8.0|^9.0"
```

According to https://getcomposer.org/doc/articles/versions.md#summary:

```
"vendor/package": ">=1.3.2", // anything above or equal to 1.3.2
```

Just FYI in case this is blocking your upgrade too.
